### PR TITLE
Revendor in dep

### PR DESCRIPTION
**Pull request by bwester**
Migrate to the "dep" tool for managing vendored dependencies.

### CODE REVIEW

**Comment by bwester** [comment]
Apparently, I have to fix the build script before I can touch the code :(

**Comment by bwester** [comment]
@DanielNi, can you take a look at this? Do you still have merge access to this repo?

**Comment by DanielNi** [comment]
Yup I still have access. Can we get rid of the `Godeps` directory too?

**Comment by bwester** [comment]
The "Revendor..." commit did remove both files in the `Godeps/` directory. I don't have that directory in my local checkout.

**Review by DanielNi — APPROVED** [review]

**Pull request merged**
